//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Collections.Generic;
    
    public partial class Defectos
    {
        public int Id { get; set; }
        public int PartesId { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaDeteccion { get; set; }
        public int ReparacionIngresoId { get; set; }
    
        public virtual Partes Partes { get; set; }
        public virtual ReparacionIngreso ReparacionIngreso { get; set; }
    }

