//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            this.DetalleVehiculo = new HashSet<DetalleVehiculo>();
            this.Partes = new HashSet<Partes>();
        }
    
        public int Id { get; set; }
        public int ResponsableId { get; set; }
        public int ModeloId { get; set; }
        public string Patente { get; set; }
        public string NumChasis { get; set; }
        public string NumMotor { get; set; }
        public string Color { get; set; }
        public System.DateTime FechaCompra { get; set; }
    
        public virtual Responsable Responsable { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual ICollection<DetalleVehiculo> DetalleVehiculo { get; set; }
        public virtual ICollection<Partes> Partes { get; set; }
    }

